### ISSUE TITLE
Problem when running sass:dev

### ISSUE THREAD

**Issue by rawzone** [matt-bailey/grunt-frontend-boilerplate#2]
Currently I have problems running the task sass:dev.

**Error:**
```
Running "watch" task
Waiting...
>> File "src/styles/main.scss" changed.

Running "sass:dev" (sass) task
OptionParser::InvalidOption: invalid option: --output-style
  Use --trace for backtrace.
Warning: 

Running "watch" task
Waiting...
```

**package.json:**
```
{
  "name": "grunt-frontend-boilerplate",
  "version": "0.0.1",
  "description": "Simple Grunt boilerplate for frontend workflow",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-concurrent": "^1.0.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-imagemin": "^0.8.1",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-uglify": "^0.6.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-contrib-sass": "^0.4.0",
    "load-grunt-config": "^0.13.1"
  },
  "dependencies": {
    "jshint-stylish": "^1.0.0",
    "time-grunt": "^1.0.0"
  }
}
```

**npm version:**
```
{
'grunt-frontend-boilerplate': '0.0.1',
  npm: '2.3.0',
  ares: '1.9.0-DEV',
  http_parser: '1.0',
  modules: '11',
  node: '0.10.35',
  openssl: '1.0.1j',
  uv: '0.10.30',
  v8: '3.14.5.9',
  zlib: '1.2.8'
}
```

Currently running under **FreeBSD 10.1-RELEASE-p4**

**Comment by matt-bailey** [comment]
Hi. I'm pretty sure I know what's happening. I can see you're using the `grunt-contrib-sass` task, rather than `grunt-sass`. What you need to do is tweak the task's options (in `grunt/sass.js`) so they match the syntax required for `grunt-contrib-sass`.

For example, `grunt-sass` uses `outputStyle: 'nested'`, but `grunt-contrib-sass` uses `style: 'nested'`.

Hope that makes sense? All the `grunt-contrib-sass` options can be found [here](https://github.com/gruntjs/grunt-contrib-sass#options).

**Comment by rawzone** [comment]
Ahh noob me, I replaced grunt-sass with grunt-contrib-sass because of problems compiling under FreeBSD at current time. It's ofcourse what the problem is - Thanks!
